client/urls.py
from django.urls import path,include
from .views import create_post,user_login,client_logout,profile_update
app_name='client'


urlpatterns = [
    path('registration/',create_post,name='registration'),
    path('login/',user_login,name='login'),
    path('logout/',client_logout,name='logout'),
    path('profile/',profile_update,name='profile')
]

gag/urls.py
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),

]+ static(settings.STATIC_URL, document_root=settings.BASE_DIR / "assets")


urlpatterns+=i18n_patterns(
 path('',include('main.urls')),
       path('client/',include('client.urls')),
    path('i18n/', include('django.conf.urls.i18n'))
)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

main/urls.py
from django.urls import path,include
from .views import index,upload_post,post_like
app_name='main'


urlpatterns = [
    path('',index,name='index'),
    path('upload/',upload_post,name='upload'),
    path('cat/<int:id>',upload_post,name='cat'),
    path('post/<int:post_id>/<str:action>/',post_like,name='post_like')
]

templates/layouts/banner.html
{% extends 'layouts/base.html'%}
{%load static%}
{% load i18n %}
{% block content%}


   {% block banner_content%}
   {%endblock%}
    

{%endblock%}

templates/layouts/base.html
{%load static%}
{% load i18n %}
{% load crispy_forms_filters %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>GAGA</title>
    <link  rel="stylesheet" type="text/css" href="{% static 'vendor/bootstrap/css/bootstrap.min.css'%}"/>
    <link  rel="stylesheet" type="text/css" href="{% static 'vendor/bootstrap-icons/fonts/bootstrap-icons.css'%}"/>
    <link  rel="stylesheet" type="text/css" href="{% static 'main/main.css'%}"/>
</head>
<body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <!-- Brand -->
    <a class="navbar-brand" href="{%url 'main:index'%}">GAG</a>

    <!-- Left side menu -->
    {%if user.is_authenticated %}
      <ul class="navbar-nav me-auto"> 
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-expanded="false">
                <img src="{{request.user.image_url}}" alt="Profil rasmi" class="rounded-circle" width="60px" height="60px">
            </a>
            <div class="dropdown-menu">
              <a class="dropdown-item" href="{%url 'client:profile'%}">{% trans 'Profile'%}</a>
              <a class="dropdown-item" href="{%url 'client:logout'%}">{% trans 'Chiqish'%}</a>
            </div>
        </li>
          <li>

               <a class="dropdown-item" href="{% url 'main:upload'%}">{% trans 'Yuklash'%}</a>
          </li>
          <li>

             <form action="{% url 'set_language' %}" method="post">
                {% csrf_token %}
                 <div class="dropdown">
                      <a class="btn btn-secondary dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-expanded="false">
                        Language
                      </a>
                     <div class="dropdown-menu">
                            <input type="hidden" name="next" value="{{ request.path }}">
                            <button type="submit" name="language" value="en">English</button><br><br>
                            <button type="submit" name="language" value="uz">Uzbek</button>
                     </div>
                 </div>
            </form>

          </li>
    {%else%}
          <ul class="navbar-nav me-auto"> 
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{%url 'client:login'%}">{% trans 'Tizimga kirish'%}</a>
              </li> 
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{%url 'client:registration'%}">{% trans "Ro'yxatdan o'tish"%}</a>
              </li> 
          </ul>
      </ul>
    {%endif%}
  </div>
</nav>


    
    <div class="container">
    {% if messages %}
        {% for message in messages %}
                <div class="{{ message.tags }} alert-dismissible fade show">
                    {{ message }}
               
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                 </div>
        {% endfor %}
    {% endif %}
    </div>
    {% block content%} {%endblock%}
    <script src="{% static 'vendor/jquery-3.7.1.min.js' %}"></script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js'%}"></script>
    <script src="{% static 'main/main.js'%}"></script>
</body>
</html>

templates/layouts/form.html
{%extends 'layouts/base.html'%}
{% load crispy_forms_tags %}
{%block content%}
<div class="container mt-5">
    <div class="card">
        <div class="card-header">
            {{title}}

        </div>
        <div class="card-body">
            <form method="post" action="" enctype="multipart/form-data" >
            {%csrf_token%}
            {{ form|crispy }}
            <button type="submit" class="btn btn-primary">{{title}}</button>

            </form>
        </div>
    </div>
</div>

{%endblock%}