gag/urls.py
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),

]+ static(settings.STATIC_URL, document_root=settings.BASE_DIR / "assets")


urlpatterns+=i18n_patterns(
 path('',include('main.urls')),
       path('client/',include('client.urls')),
    path('i18n/', include('django.conf.urls.i18n'))
)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

main/urls.py
from django.urls import path,include
from .views import index,upload_post,post_like
app_name='main'


urlpatterns = [
    path('',index,name='index'),
    path('upload/',upload_post,name='upload'),
    path('cat/<int:id>',upload_post,name='cat'),
    path('post/<int:post_id>/<str:action>/',post_like,name='post_like')
]

templates/widgets/post.html
<ul class="list-group list-group-flush">
            {%for p in posts %}
                <li class="list-group-item">{{p.user}} -- {{p.category}}</li>
                <li class="list-group-item"><img style="width:400px; height: 400px;" src="{{ p.file.url }}"/><a href="#" ></a></li>
                <li  class="list-group-item">
                    <a href="{% url 'main:post_like' p.id 'like'%}?return={{request.get_full_path}}">👍 {{ p.like }}</a> 
                    <a href="{% url 'main:post_like'  p.id 'dislike'%}?return={{request.get_full_path}}">👎{{ p.dislike }}</a>
                    <a href="#">💬{{ p.comment }}</a></li>  
            {%endfor%}
    
                <!-- {{posts}}<br>
                Has Previous: {{posts.has_previous}}<br>
                Has Next:{{posts.has_next}}<br>
                Current Page :{{posts.number}}<br>
                Number of pages:{{posts.paginator.num_pages}}

                <hr><br/><br/> -->
                <nav aria-label="Page navigation example">
                  <ul class="pagination justify-content-center">
                    {%if posts.has_previous %}
                        <li class="page-item"><a class="page-link" href="?page=1">&laquo First</a></li>
                        <li class="page-item"><a class="page-link" href="?page={{posts.previous_page_number}}">Previous</a></li>
                    {% endif %}
                    
                    <!-- <li class="page-item"><a class="page-link" href="#">Page {{posts.number}} of {{posts.paginator.num_pages}}</a></li> -->
                    {% for i in nums %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{forloop.counter}}">
                            {{forloop.counter}}
                        </a> 
                    </li>
                         
                    {% endfor %}
                    {% if posts.has_next%}
                      <li class="page-item"><a class="page-link" href="?page={{posts.next_page_number}}" >next</a></li>
                        <li class="page-item"><a class="page-link" href="?page={{posts.paginator.num_pages}}" >last &raquo</a></ul>
                    {% endif %}
                  </ul>
                </nav>
            
    </ul>